spring.application.name=SalesTracker

spring.datasource.url=jdbc:postgres://localhost:5432/sales-service
spring.datasource.username=postgres
spring.datasource.password=postgres

# Show the SQL queries in the console
spring.jpa.show-sql=true
# Format the output SQL string nicely for readability
spring.jpa.properties.hibernate.format_sql=true
# Bind parameter values inside the logging output (instead of '?')
logging.level.org.hibernate.orm.jdbc.bind=trace