spring.application.name=SalesTracker

spring.datasource.url=jdbc:postgresql://localhost:5432/Order-Service-database
spring.datasource.username=postgres
spring.datasource.password=postgres

# Show the SQL queries in the console
spring.jpa.show-sql=true
# Format the output SQL string nicely for readability
spring.jpa.properties.hibernate.format_sql=true
# Bind parameter values inside the logging output (instead of '?')
logging.level.org.hibernate.orm.jdbc.bind=trace

spring.flyway.url=jdbc:postgresql://localhost:5432/Order-Service-database
spring.flyway.user=postgres
spring.flyway.password=postgres
#spring.flyway.schemas=postgresql
spring.flyway.locations=db/migrations/postgres