CREATE TABLE ORDER_STATUS (
    ID     SERIAL      PRIMARY KEY,
    STATUS VARCHAR(20) NOT NULL UNIQUE CHECK (STATUS ~ '\S')
);

CREATE TABLE ORDERS (
    ID              UUID           PRIMARY KEY,
    RETAILER_ID     UUID           NOT NULL,
    CUSTOMER_ID     UUID           NOT NULL,
    ISSUED_AT       TIMESTAMP      NOT NULL,
    ORDER_STATUS_ID INTEGER        REFERENCES ORDER_STATUS(ID),
    CREATED_AT      TIMESTAMP      NOT NULL,
    UPDATED_AT      TIMESTAMP      NOT NULL CHECK (UPDATED_AT >= CREATED_AT),
    DELETED_AT      TIMESTAMP               CHECK (DELETED_AT >  CREATED_AT AND DELETED_AT > UPDATED_AT)
);

CREATE TABLE ITEMS (
    ID             SERIAL         PRIMARY KEY,
    ORDER_ID       UUID           REFERENCES ORDERS(ID),
    PRODUCT_ID     UUID           NOT NULL,
    PRODUCT_NAME   VARCHAR(50)    NOT NULL CHECK (PRODUCT_NAME ~ '\S'),
    PRODUCT_SKU    VARCHAR(20)    NOT NULL CHECK (PRODUCT_SKU  ~ '\S'),
    QUANTITY       INTEGER        NOT NULL CHECK (QUANTITY > 0),
    UNIT_PRICE     NUMERIC(12, 2) NOT NULL CHECK (UNIT_PRICE >= 0),
    TOTAL_DISCOUNT NUMERIC(12, 2) NOT NULL CHECK (TOTAL_DISCOUNT >= 0),
    CREATED_AT     TIMESTAMP      NOT NULL,
    UPDATED_AT     TIMESTAMP      NOT NULL CHECK (UPDATED_AT >= CREATED_AT)
);

INSERT INTO ORDER_STATUS (STATUS)
VALUES ('OPEN');
INSERT INTO ORDER_STATUS (STATUS)
VALUES ('CLOSED');
INSERT INTO ORDER_STATUS (STATUS)
VALUES ('CANCELED');
INSERT INTO ORDER_STATUS (STATUS)
VALUES ('WAITING_CONFIRMATION');
INSERT INTO ORDER_STATUS (STATUS)
VALUES ('CONFIRMED');