CREATE TABLE DELINQUENCY_STATUS (
    ID     SERIAL      PRIMARY KEY,
    STATUS VARCHAR(50) NOT NULL UNIQUE CHECK(STATUS ~ '\S')
);

CREATE TABLE CUSTOMERS (
    ID                    UUID         PRIMARY KEY,
    NAME                  VARCHAR(100) NOT NULL,
    EMAIL                 VARCHAR(100) NOT NULL UNIQUE CHECK (EMAIL ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    DELINQUENCY_STATUS_ID INTEGER      REFERENCES DELINQUENCY_STATUS(ID),
    CREATED_AT            TIMESTAMP    NOT NULL,
    UPDATED_AT            TIMESTAMP    NOT NULL CHECK (UPDATED_AT >= CREATED_AT),
    DELETED_AT            TIMESTAMP             CHECK (DELETED_AT >  CREATED_AT AND DELETED_AT > UPDATED_AT)
);

CREATE TABLE PHONE_NUMBERS (
    ID           SERIAL      PRIMARY KEY,
    CUSTOMER_ID  UUID        REFERENCES CUSTOMERS(ID),
    COUNTRY_CODE INTEGER     NOT NULL,
    NUMBER       VARCHAR(20) NOT NULL,
    CREATED_AT   TIMESTAMP   NOT NULL,
    UPDATED_AT   TIMESTAMP   NOT NULL CHECK (UPDATED_AT >= CREATED_AT),
    DELETED_AT   TIMESTAMP            CHECK (DELETED_AT >  CREATED_AT AND DELETED_AT > UPDATED_AT)
);

CREATE TABLE ORDERS (
    ID          UUID           PRIMARY KEY,
    CUSTOMER_ID UUID           REFERENCES CUSTOMERS(ID),
    TOTAL_ITEMS INTEGER        NOT NULL,
    TOTAL_VALUE NUMERIC(12, 2) NOT NULL,
    CREATED_AT  TIMESTAMP      NOT NULL,
    UPDATED_AT  TIMESTAMP      NOT NULL CHECK (UPDATED_AT >= CREATED_AT),
    DELETED_AT  TIMESTAMP               CHECK (DELETED_AT >  CREATED_AT AND DELETED_AT > UPDATED_AT)
);

CREATE TABLE ITEMS (
    ID             SERIAL         PRIMARY KEY,
    ORDER_ID       UUID           REFERENCES ORDERS(ID),
    PRODUCT_ID     UUID           NOT NULL,
    QUANTITY       INTEGER        NOT NULL CHECK (QUANTITY > 0),
    UNIT_PRICE     NUMERIC(12, 2) NOT NULL CHECK (UNIT_PRICE >= 0),
    TOTAL_DISCOUNT NUMERIC(12, 2) NOT NULL CHECK (TOTAL_DISCOUNT >= 0),
    CREATED_AT     TIMESTAMP      NOT NULL,
    UPDATED_AT     TIMESTAMP      NOT NULL CHECK (UPDATED_AT >= CREATED_AT),
    DELETED_AT     TIMESTAMP               CHECK (DELETED_AT >  CREATED_AT AND DELETED_AT > UPDATED_AT)
);