CREATE TABLE PHONE_NUMBERS (
    ID           SERIAL      PRIMARY KEY,
    COUNTRY_CODE INTEGER     NOT NULL,
    NUMBER       VARCHAR(20) NOT NULL,
    CREATED_AT   TIMESTAMP   NOT NULL,
    UPDATED_AT   TIMESTAMP   NOT NULL CHECK (UPDATED_AT >= CREATED_AT),
    DELETED_AT   TIMESTAMP   NOT NULL CHECK (DELETED_AT >  CREATED_AT)
);

CREATE TABLE DELINQUENCY_STATUS (
    ID SERIAL PRIMARY KEY,
    STATUS VARCHAR(20) UNIQUE NOT NULL CHECK(STATUS ~ '\S')
);

CREATE TABLE CUSTOMERS (
    ID                    UUID         PRIMARY KEY,
    NAME                  VARCHAR(100) NOT NULL,
    EMAIL                 VARCHAR(100) UNIQUE NOT NULL CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    PHONE_NUMBER_ID       INTEGER      REFERENCES PHONE_NUMBER(ID),
    DELINQUENCY_STATUS_ID INTEGER      REFERENCES DELINQUENCY_STATUS(ID),
    UPDATED_AT            TIMESTAMP    NOT NULL CHECK (UPDATED_AT >= CREATED_AT),
    DELETED_AT            TIMESTAMP             CHECK (DELETED_AT >  CREATED_AT)
);

CREATE TABLE ORDER_ITEM (
    ID SERIAL PRIMARY KEY
);

CREATE TABLE ORDER (
    ID UUID PRIMARY KEY
);

CREATE TABLE INSTALLMENT_STATUS (
    ID     SERIAL      PRIMARY KEY,
    STATUS VARCHAR(20) UNIQUE NOT NULL CHECK(STATUS ~ '\S')
);

CREATE TABLE INSTALLMENTS (
    ID UUID PRIMARY KEY,
);

CREATE TABLE PAYMENT_METHOD (
    ID SERIAL PRIMARY KEY,
    METHOD VARCHAR(20) UNIQUE NOT NULL CHECK(METHOD ~ '\S')
);

CREATE TABLE PAYMENTS (
    ID                 UUID           PRIMARY KEY,
    INSTALLMENT_ID     UUID           REFERENCES INSTALLMENT(ID),
    PAYMENT_METHOD_ID  INTEGER        REFERENCES PAYMENT_METHOD(ID),
    VALUE              NUMERIC(12, 2) NOT NULL CHECK (PRICE >= 0),
    PAID_AT            TIMESTAMP,
    INSTALLMENT_NUMBER INTEGER        NOT NULL CHECK (INSTALLMENT_NUMBER > 0),
    CREATED_AT         TIMESTAMP      NOT NULL,
    UPDATED_AT         TIMESTAMP      NOT NULL CHECK (UPDATED_AT >= CREATED_AT),
    DELETED_AT         TIMESTAMP      NOT NULL CHECK (DELETED_AT >  CREATED_AT)
);